import noteBot as nB
nB.newPage(130, 130)
nB.font("Times")
nB.text("ToTAVAT.", (10, 10))
nB.openTypeFeatures(kern=False)
nB.text("ToTAVAT.", (10, 30))
nB.openTypeFeatures(kern=True)
nB.text("ToTAVAT.", (10, 50))
# add tracking
nB.tracking(10)
nB.text("ToTAVAT.", (10, 70))
nB.openTypeFeatures(kern=False)
nB.text("ToTAVAT.", (10, 90))
nB.openTypeFeatures(kern=True)
nB.text("ToTAVAT.", (10, 110))