import noteBot as nB
nB.newPage(200, 200)
nB.text("hello world", (10, 10))
nB.fill(1, 0, 0)
nB.text("foo bar", (10, 30))
nB.fill(1, 0, 1)
nB.stroke(0, 1, 0)
nB.strokeWidth(2)
nB.font("Times", 50)
nB.text("foo bar", (10, 50))
nB.fill(None)
nB.stroke(0, 1, 0)
nB.strokeWidth(1)
nB.line((0, 50), (nB.width(), 50))
nB.stroke(None)
nB.fill(0, 1, 1)
nB.fontSize(20)
nB.text("foo bar", (nB.width()*.5, 100), align="right")
nB.text("foo bar", (nB.width()*.5, 120), align="center")
nB.text("foo bar", (nB.width()*.5, 140), align="left")
# test empty text https://github.com/typemytype/drawbot/issues/389
nB.text("", (0, 0))
