import noteBot as nB

transparent = nB.Color(0, 0, 0, 0)

nB.newPage(200, 200)
nB.text("hello world", nB.Point(10, 10))
nB.fill(nB.Color(1, 0, 0))
nB.text("foo bar", nB.Point(10, 30))
nB.fill(nB.Color(1, 0, 1))
nB.stroke(nB.Color(0, 1, 0))
nB.strokeWidth(2)
nB.font("Times", 50)
nB.text("foo bar", nB.Point(10, 50))
nB.fill(transparent)
nB.stroke(nB.Color(0, 1, 0))
nB.strokeWidth(1)
nB.line(nB.Point(0, 50), nB.Point(nB.width(), 50))
nB.stroke(transparent)
nB.fill(nB.Color(0, 1, 1))
nB.fontSize(20)
nB.text("foo bar", nB.Point(nB.width()*.5, 100), align=nB.Alignment.right)
nB.text("foo bar", nB.Point(nB.width()*.5, 120), align=nB.Alignment.center)
nB.text("foo bar", nB.Point(nB.width()*.5, 140), align=nB.Alignment.left)
# test empty text https://github.com/typemytype/drawbot/issues/389
nB.text("", nB.Point(0, 0))
